# Generated by Django 5.2.8 on 2025-11-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_workhour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhour',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='workhour',
            name='hours',
            field=models.FloatField(),
        ),
    ]
