# Generated by Django 5.2.8 on 2025-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_worktag_delete_tags_workhour_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhour',
            name='hours',
        ),
        migrations.AddField(
            model_name='workhour',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workhour',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
