# Generated by Django 5.2.8 on 2025-12-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_machine_machineworklog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machineworklog',
            unique_together=set(),
        ),
    ]
